(() => {
 const products=[['python-part1','Python · Part 1',30,['python1']],['python-bundle','Python · Both parts',59,['python1','python2']],['numpy-part1','NumPy · Part 1',39,['numpy1']],['numpy-part2','NumPy · Part 2',39,['numpy2']],['numpy-bundle','NumPy · Both notes',59,['numpy1','numpy2']],['numpy-complete','NumPy · Complete package',99,['numpy1','numpy2','numpyzip']]];
 let cart=[];try{cart=JSON.parse(localStorage.getItem('mahi-cart-v2')||'[]');if(!Array.isArray(cart))cart=[];}catch{}
 cart=cart.filter(id=>products.some(p=>p[0]===id));let owned=[],busy=false;
 const section=document.createElement('section');section.id='shop';section.innerHTML='<div class="sec-inner"><p class="eyebrow">01 / CHOOSE YOUR STARTING POINT</p><h2>Less confusion. More understanding.</h2><p>NumPy: ₹39 per part · Both notes ₹59 — Save ₹19 · Complete package ₹99</p><div id="storeProducts" class="catalog-grid"></div><div class="store-panel"><h3>Your cart</h3><div id="cartItems"></div><button class="btn-primary" id="checkout">Checkout with Razorpay</button><p id="storeStatus" role="status"></p></div><div class="store-panel"><h3>My purchases</h3><p>Log in with the account you used at checkout to access your notes anytime.</p><button class="btn-ghost" id="restoreStore">Restore purchases</button><div id="ownedNotes"></div></div></div>';
 document.querySelector('#notes').before(section);
 const style=document.createElement('style');style.textContent='#shop{padding:80px 5%;scroll-margin-top:90px}#shop .sec-inner{max-width:1200px;margin:auto}#shop h2{font-size:clamp(28px,4vw,48px);margin-bottom:16px}#storeProducts{margin:28px 0}#storeProducts article{padding:24px;gap:16px}#storeProducts h3{font-size:24px}#storeProducts button{margin-top:12px} .store-panel{margin:24px 0;padding:24px;border:1px solid var(--gray2);border-radius:18px}.store-line{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:14px 0;flex-wrap:wrap}#storeStatus{padding-top:14px}';document.head.append(style);
 const nav=document.createElement('button');nav.className='btn-login';nav.textContent='Cart / Purchases';nav.onclick=()=>section.scrollIntoView({behavior:'smooth'});document.querySelector('.nav-tools').prepend(nav);
 function normalize(){cart=[...new Set(cart)];if(cart.includes('numpy-complete'))cart=cart.filter(id=>!['numpy-part1','numpy-part2','numpy-bundle'].includes(id));else if(cart.includes('numpy-bundle')||(cart.includes('numpy-part1')&&cart.includes('numpy-part2')))cart=[...cart.filter(id=>!id.startsWith('numpy-')),'numpy-bundle'];if(cart.includes('python-bundle'))cart=cart.filter(id=>id!=='python-part1');localStorage.setItem('mahi-cart-v2',JSON.stringify(cart));}
 const status=s=>document.querySelector('#storeStatus').textContent=s;
 async function api(path,options={}){if(!window.currentUser){openM('login');throw Error('Please log in first.');}const token=await window.currentUser.getIdToken();const r=await fetch('/api/'+path,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token}});let data;try{data=await r.json()}catch{throw Error('Store backend is not configured yet.');}if(!r.ok)throw Error(data.error||'Request failed');return data;}
 function draw(){normalize();document.querySelector('#storeProducts').innerHTML=products.map(([id,title,price,assets])=>`<article class="catalog-card"><span class="eyebrow">${id.startsWith('numpy')?'NUMPY / DATA SCIENCE':'PYTHON / FOUNDATIONS'}</span><h3>${title}</h3><p>${id==='numpy-complete'?'Both notes + projects + practice sheet (ZIP)':id==='numpy-bundle'?'Part 1 + Part 2 · Save ₹19':'Personal access · One-time payment'}</p><strong>₹${price}</strong><button class="btn-primary" data-add="${id}" ${assets.every(a=>owned.includes(a))?'disabled':''}>${assets.every(a=>owned.includes(a))?'Purchased':cart.includes(id)?'In cart':'Add to cart'}</button></article>`).join('');document.querySelector('#cartItems').innerHTML=cart.length?cart.map(id=>{const p=products.find(p=>p[0]===id);return `<div class="store-line"><span>${p[1]} · ₹${p[2]}</span><button class="btn-ghost" data-remove="${id}">Remove</button></div>`}).join('')+`<p><strong>Total: ₹${cart.reduce((sum,id)=>sum+products.find(p=>p[0]===id)[2],0)}</strong></p>`:'Your cart is empty.';document.querySelector('#checkout').disabled=busy||!cart.length;document.querySelector('#ownedNotes').innerHTML=owned.length?owned.map(a=>`<div class="store-line"><span>${({python1:'Python Part 1',python2:'Python Part 2',numpy1:'NumPy Part 1',numpy2:'NumPy Part 2',numpyzip:'NumPy projects & practice ZIP'})[a]||'Notes'}</span><button class="btn-primary" data-read="${a}">Open ${a==='numpyzip'?'package':'notes'}</button></div>`).join(''):'No purchases loaded.';}
 window.clearPurchases=()=>{owned=[];document.querySelector('#pdfFrame').src='about:blank';document.querySelector('#pdfViewer').style.display='none';draw();};
 window.refreshPurchases=async()=>{const user=window.currentUser;if(!user){window.clearPurchases();return;}try{const d=await api('purchases');if(window.currentUser?.uid!==user.uid)return;owned=d.assets;window.hasPaid=owned.includes('python1')&&owned.includes('python2');draw();status('Purchases refreshed.');}catch(e){status(e.message)}};
 async function read(asset){try{const user=window.currentUser;const d=await api('access?asset='+encodeURIComponent(asset));if(window.currentUser?.uid!==user?.uid)return;document.querySelector('#pdfViewer').style.display='block';document.querySelector('#viewerLabel').textContent=asset==='numpyzip'?'NumPy complete package':'Your purchased notes';document.querySelector('#openReaderTab').href=d.url;document.querySelector('#pdfFrame').src=d.url;document.querySelector('#pdfViewer').scrollIntoView({behavior:'smooth'});}catch(e){status(e.message);section.scrollIntoView({behavior:'smooth'});}}
 window.checkoutCart=async()=>{if(busy||!cart.length)return;if(!window.currentUser){openM('login');status('Log in, then return to your cart to pay.');return;}busy=true;draw();try{status('Creating your order…');const order=await api('orders',{method:'POST',body:JSON.stringify({items:cart})});const checkout=new Razorpay({key:order.key,order_id:order.orderId,amount:order.amount,currency:'INR',name:"Mahirrior",prefill:{email:window.currentUser.email||'',name:window.currentUser.displayName||''},handler:async response=>{try{status('Verifying payment…');await api('verify',{method:'POST',body:JSON.stringify(response)});cart=cart.filter(id=>!order.items.includes(id));normalize();await window.refreshPurchases();status('Payment verified. Your notes are available in My purchases.');}catch(e){status(e.message+' If charged, use Restore purchases.');}finally{busy=false;draw();}},modal:{ondismiss:()=>{busy=false;draw();status('Checkout closed. If charged, use Restore purchases.');}},theme:{color:'#c9502d'}});checkout.on('payment.failed',()=>status('Payment failed. You can retry checkout.'));checkout.open();}catch(e){status(e.message);busy=false;draw();}};
 section.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.add){cart.push(b.dataset.add);draw();status('Added to cart. Bundle savings applied automatically.');}if(b.dataset.remove){cart=cart.filter(x=>x!==b.dataset.remove);draw();}if(b.dataset.read)read(b.dataset.read);});document.querySelector('#checkout').onclick=window.checkoutCart;document.querySelector('#restoreStore').onclick=()=>window.refreshPurchases();
 window.doPayment=window.checkoutCart;window.restoreAccess=()=>{section.scrollIntoView({behavior:'smooth'});window.refreshPurchases();};window.handleGetAccess=()=>{section.scrollIntoView({behavior:'smooth'});};window.showPDF=()=>read('python1');window.switchPart=part=>read(part==='part2'?'python2':'python1');
 draw();
})();
